# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'elevation_path.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets, QtWebEngineWidgets

from mplwidget import MplWidget


class UiMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1113, 950)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pb_do_path = QtWidgets.QPushButton(self.centralwidget)
        self.pb_do_path.setGeometry(QtCore.QRect(290, 110, 541, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_do_path.sizePolicy().hasHeightForWidth())
        self.pb_do_path.setSizePolicy(sizePolicy)
        self.pb_do_path.setStyleSheet("background-color: rgb(115, 210, 22);")
        self.pb_do_path.setObjectName("pb_do_path")
        self.webView = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.webView.setGeometry(QtCore.QRect(0, 159, 1101, 511))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webView.sizePolicy().hasHeightForWidth())
        self.webView.setSizePolicy(sizePolicy)
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1101, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.rb_osm_map = QtWidgets.QRadioButton(self.layoutWidget)
        self.rb_osm_map.setStyleSheet("color: rgb(1, 5, 123);")
        self.rb_osm_map.setChecked(True)
        self.rb_osm_map.setObjectName("rb_osm_map")
        self.horizontalLayout_4.addWidget(self.rb_osm_map, 0, QtCore.Qt.AlignHCenter)
        self.rb_google_map = QtWidgets.QRadioButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_google_map.sizePolicy().hasHeightForWidth())
        self.rb_google_map.setSizePolicy(sizePolicy)
        self.rb_google_map.setStyleSheet("color: rgb(1, 5, 123);")
        self.rb_google_map.setObjectName("rb_google_map")
        self.horizontalLayout_4.addWidget(self.rb_google_map, 0, QtCore.Qt.AlignHCenter)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 40, 1101, 71))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.le_lat_a = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.le_lat_a.setStyleSheet("background-color: rgb(179, 229, 252);")
        self.le_lat_a.setAlignment(QtCore.Qt.AlignCenter)
        self.le_lat_a.setObjectName("le_lat_a")
        self.verticalLayout_6.addWidget(self.le_lat_a, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.le_lng_a = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.le_lng_a.setStyleSheet("background-color: rgb(179, 229, 252);")
        self.le_lng_a.setAlignment(QtCore.Qt.AlignCenter)
        self.le_lng_a.setObjectName("le_lng_a")
        self.verticalLayout_7.addWidget(self.le_lng_a, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.le_lat_b = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.le_lat_b.setStyleSheet("background-color: rgb(179, 229, 252);")
        self.le_lat_b.setAlignment(QtCore.Qt.AlignCenter)
        self.le_lat_b.setObjectName("le_lat_b")
        self.verticalLayout_8.addWidget(self.le_lat_b, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.le_lng_b = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.le_lng_b.setStyleSheet("background-color: rgb(179, 229, 252);")
        self.le_lng_b.setAlignment(QtCore.Qt.AlignCenter)
        self.le_lng_b.setObjectName("le_lng_b")
        self.verticalLayout_9.addWidget(self.le_lng_b, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.gv_osm_plot = MplWidget(self.centralwidget)
        self.gv_osm_plot.setEnabled(True)
        self.gv_osm_plot.setGeometry(QtCore.QRect(0, 670, 1101, 230))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gv_osm_plot.sizePolicy().hasHeightForWidth())
        self.gv_osm_plot.setSizePolicy(sizePolicy)
        self.gv_osm_plot.setObjectName("gv_osm_plot")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1113, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pb_do_path.setText(_translate("MainWindow", "Elevation path"))
        self.rb_osm_map.setText(_translate("MainWindow", "Offline OSM map"))
        self.rb_google_map.setText(_translate("MainWindow", "Online Google map"))
        self.label_6.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-size:12pt;\">Lat A</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-size:12pt;\">Lng A</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-size:12pt;\">Lat B</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-size:12pt;\">Lng B</span></p></body></html>"))
